[package]
name = "heat"
version = "0.1.0"
authors = ["fi-le <info at fi-le.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.19.0"

[profile.release]
opt-level = "s"
